name: Generate icons list

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate icons/list.json
        run: node icons/generate-list.mjs

      - name: Commit and push if list.json changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add icons/list.json
          git diff --cached --quiet || git commit -m "chore: update icons/list.json"
          git push
